### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-linear-algebra#12]
As per https://github.com/elm-community/Manifesto/issues/27, and in particular this discussion: https://github.com/elm-community/Manifesto/issues/27#issuecomment-219725390.

**Comment by fredcy** [comment]
This package has already been published with four tags/versions as 'elm-community/elm-linear-algebra'. If we change this name of this repository, what happens when someone tries to install via the old package name? Also, do we need to publish each of the four tagged versions under the new name (much as someone did after we forked the repo here)?

**Comment by jvoigtlaender** [comment]
The only API change that happened in any of these releases was renaming `makeFrustrum` to `makeFrustum`, right? Assuming that that was a typo correction, I guess nobody would ever want to go back to the original API. So I do not think it would be necessary to preserve old tags/versions. A new `elm-community/linear-algebra` version `1.0.0` should be good enough.

**Comment by jvoigtlaender** [comment]
About trying to install the package under its old name (not concerning the version numbers), that's a problem all the currently published `elm-community/elm-...` packages have, as well as the previously published `circuithub/...` packages that were transferred to `elm-community`. There is not something special here, is there?

Well, one thing: We would need to get Evan to change the whitelisting on the package site to mention the new repo name. Which might actually be a block.

**Comment by fredcy** [comment]
OK, here's my plan:
1. Create a new empty elm-community/linear-algebra repo.
2. Clone the elm-linear-algebra repo locally, update its origin to be the new linear-algebra, and push up everything except tags.
3. Delete local tags: `git tag | xargs git tag -d`
4. Create 1.0.0 tag on linear-algebra.
5. Publish linear-algebra as version 1.0.0.  Since the package has native code this may get blocked as it needs to be whitelisted by Evan.
6. Once linear-algebra 1.0.0 is published, update elm-linear-algebra to declare itself as "deprecated" and referring user to the new linear-algebra package. Publish those changes.
7. Copy and paste any open issues from elm-linear-algebra to linear-algebra.

This procedure will not carry over any tags from elm-linear-algebra to linear-algebra.

Any comments?

**Comment by jvoigtlaender** [comment]
Maybe contact Evan first, to ask whether he is willing to unblock 4.? It would be a pity if the plan breaks down midway through because the whitelisting is not happening.

**Comment by fredcy** [comment]
OK, I have reached out to Evan via Slack.

**Comment by fredcy** [comment]
Evan approved this plan. I'm now blocked, waiting on the above PR to be merged.

**Comment by fredcy** [comment]
Done in 0.18 Elm release.
