### ISSUE TITLE
Revisit open issues and pull requests from origin?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-linear-algebra#4]
That is, go through https://github.com/johnpmayer/elm-linear-algebra/issues and https://github.com/johnpmayer/elm-linear-algebra/pulls and see which ones might be useful to add here?

**Comment by jvoigtlaender** [comment]
What I say in [this comment](https://github.com/elm-community/elm-webgl/issues/5#issuecomment-171332705) applies here as well.

**Comment by nphollon** [comment]
I looked through them yesterday and released the doc fixes as 1.0.1. Sorry for not consulting anybody, but I thought they were uncontroversial and was still on a high from finally getting the package released :-P

The only other issues are year-old feature requests. Since this package exists primarily as a dependency for elm-webgl, we probably shouldn't bother with them.

Is there anything I missed?

**Comment by jvoigtlaender** [comment]
Looks like you already took care of everything worth taking care of. :smile:
