### ISSUE TITLE
Support for Mat2 and Mat3?

### ISSUE THREAD

**Issue by mchav** [elm-community/elm-linear-algebra#7]
Are there plans to support these at any point?

**Comment by mgold** [comment]
Not at the moment. They aren't included in the JS library this is based on. Also this library is meant of web graphics; you use 2x2 or 3x3 matrices in WebGL basically never.

**Comment by mchav** [comment]
I came across a couple of use cases where I needed to use mat3's similar to this issue:
https://github.com/johnpmayer/elm-linear-algebra/issues/8

I'm guessing this is off the table right now? 

Sorry to be a bother with all this.

**Comment by nphollon** [comment]
I'm afraid it's off the table. But you shouldn't feel bad about asking, I think it's a legitimate request.

What Elm really needs is a good linear algebra package that's written entirely in Elm. (It's on my to-do list, but I don't have time at the moment. Interested in taking the challenge?)

The reason we are being sticklers about adding to this package is because it's implemented in JavaScript. You saw the perils of this in #9. If makeFrustum had been implemented in Elm, those bugs would have been caught at compile-time.

The only reason this library is still around is because elm-webgl depends on it. And we are only keeping elm-webgl until we replace it with something better post-0.17.

**Comment by mchav** [comment]
@nphollon I'd love to. I was looking into Ed Kmett's Haskell implementation and that seemed quite promising as a concept. Also i was looking at LambdaCube as a template for 3D graphics. I could invest the next few months into the summer working with you on both fronts if you're interested.

**Comment by mgold** [comment]
@ChavXO [Here](https://gist.github.com/mgold/c58b2e8dcbe808b82d5a) is a C++ file from my old college prof that may be useful.
